# Shorthand commands for peek development.
# Install just: https://github.com/casey/just

default:
    just --list

# Run all workspace tests
test:
    cargo test --workspace

# Format code (fix)
fmt:
    cargo fmt

# Check formatting only (CI)
fmt-check:
    cargo fmt --check

# Lint with Clippy (must pass with -D warnings)
lint:
    cargo clippy --workspace --all-targets -- -D warnings

# Format + lint + test (full check before PR)
check: fmt-check lint test
    @echo "All checks passed."

# Build release binaries for all workspace members
release:
    cargo build --release --workspace

# Build and copy man page to man/peek.1 (generated by peek-cli build.rs)
man:
    cargo build -p peek-cli
    mkdir -p man
    sh -c 'f=$$(find target -path "*peek-cli-*" -name peek.1 -type f 2>/dev/null | head -1); [ -n "$$f" ] && cp "$$f" man/peek.1'
    @echo "Man page written to man/peek.1"

# Run cargo-deny (install with: cargo install cargo-deny)
deny:
    cargo deny check

# Build debug binaries (default dev build)
build:
    cargo build --workspace

# Run peek with args (e.g. just run -- 1234 --resources)
run args:
    cargo run -p peek-cli -- {{args}}
