Name:           peek-cli
Version:        1.0.0
Release:        1%{?dist}
Summary:        The Process Intelligence Tool for Linux

License:        MIT
URL:            https://github.com/ankittk/peek
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  rust >= 1.70
BuildRequires:  cargo
BuildRequires:  openssl-devel

Requires:       glibc

%description
peek is a single, unified CLI tool that explains what a Linux process is,
what it is doing, how it is consuming your system resources, and gives you
intelligent options to act on that knowledge — all in plain English.

It consolidates ps, top, lsof, ss, strace, and /proc inspection into one
command with colour output, a live TUI dashboard, signal impact analysis,
environment variable redaction, and optional JSON/Markdown/HTML/PDF export.

%package -n peekd
Summary:        Background daemon for peek resource history and alerting
Requires:       peek-cli = %{version}-%{release}
%description -n peekd
peekd is the optional background daemon that powers peek's --history flag.
It samples watched processes every second into a ring buffer, exposes a
Unix socket for CLI queries, and fires configurable CPU/memory alerts.

%prep
%autosetup

%build
cargo build --release --workspace
cargo build --release -p peek-cli
# Generate man page and completions
OUT_DIR=$(cargo build --release -p peek-cli 2>&1 | grep "^cargo:warning=man page" | sed 's/.*written to //' | xargs dirname 2>/dev/null || true)

%install
install -Dm755 target/release/peek     %{buildroot}%{_bindir}/peek
install -Dm755 target/release/peekd    %{buildroot}%{_bindir}/peekd

# Man page for peek (section 1), generated by peek-cli build.rs
if [ -f "$(find target -name 'peek.1' -newer Cargo.toml 2>/dev/null | head -1)" ]; then
  install -Dm644 "$(find target -name 'peek.1' | head -1)" \
      %{buildroot}%{_mandir}/man1/peek.1
fi

# Man page for peekd (section 8), generated by peekd build.rs
if [ -f "$(find target -name 'peekd.8' -newer Cargo.toml 2>/dev/null | head -1)" ]; then
  install -Dm644 "$(find target -name 'peekd.8' | head -1)" \
      %{buildroot}%{_mandir}/man8/peekd.8
fi

# Shell completions
for f in $(find target -name 'peek.bash' -o -name '_peek' -o -name 'peek.fish' 2>/dev/null); do
  case "$f" in
    *.bash) install -Dm644 "$f" %{buildroot}%{_datadir}/bash-completion/completions/peek ;;
    */_peek) install -Dm644 "$f" %{buildroot}%{_datadir}/zsh/site-functions/_peek ;;
    *.fish) install -Dm644 "$f" %{buildroot}%{_datadir}/fish/vendor_completions.d/peek.fish ;;
  esac
done

# systemd unit for peekd
install -Dm644 packaging/peekd.service %{buildroot}%{_unitdir}/peekd.service

%post -n peekd
%systemd_post peekd.service

%preun -n peekd
%systemd_preun peekd.service

%postun -n peekd
%systemd_postun_with_restart peekd.service

%files
%license LICENSE
%doc README.md
%{_bindir}/peek
%{_mandir}/man1/peek.1*
%{_datadir}/bash-completion/completions/peek
%{_datadir}/zsh/site-functions/_peek
%{_datadir}/fish/vendor_completions.d/peek.fish

%files -n peekd
%{_bindir}/peekd
%{_unitdir}/peekd.service
%{_mandir}/man8/peekd.8*

%changelog
* Fri Feb 28 2026 Ankit <ankittkmail@gmail.com> - 1.0.0-1
- Initial packaging

